<a href="https://colab.research.google.com/github/abishekr19/flyrank-ml-internship-starter/blob/main/work/notebooks/w01_research_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*Name your lane — or say 'freestyle' and describe your own question. One short paragraph: why this one?*

### My lane: Student Performance Prediction

I want to study whether a student's academic performance can be predicted using factors such as attendance, internal marks, study time, and previous academic performance. I chose this topic because predicting students who may need additional academic support can help teachers take action early and improve student outcomes.

In [1]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 2. The question: decision, action, cost of a wrong call

*What decision does your work improve? Who acts on it? What does a wrong recommendation cost?*

### Decision, Action, and Cost

**Question:** Can we predict whether a student is at risk of getting low academic marks?

**Decision:** Identify students who may be at risk of poor academic performance.

**Action:** Teachers or mentors can provide additional classes, guidance, and academic support to those students.

**Cost of a wrong recommendation:** If a student is incorrectly predicted as being at risk, unnecessary support may be provided. If a student who actually needs help is predicted as performing well, the student may miss important academic support.

In [2]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

### Quick look at the data

The dataset contains 30,000 pages across 44 columns. A quick check shows that 6,068 pages have at least 100 impressions but zero clicks. More importantly, 4,166 pages have at least 250 impressions but still receive zero clicks. This suggests that a significant number of pages are getting visibility in search but are not generating clicks, making content improvement and search discoverability a useful area to investigate over the next 7 weeks.

In [7]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

# Pages with 100+ impressions but zero clicks
zero_click_100 = df[
    (df["impressions_90d"] >= 100) &
    (df["clicks_90d"] == 0)
]

print("Total pages:", len(df))
print("Total columns:", len(df.columns))
print("Pages with 100+ impressions but 0 clicks:", len(zero_click_100))

# Pages with 250+ impressions but zero clicks
zero_click_250 = df[
    (df["impressions_90d"] >= 250) &
    (df["clicks_90d"] == 0)
]

print("Pages with 250+ impressions but 0 clicks:", len(zero_click_250))

# Position tier distribution
print("\nPosition tiers among 250+ impression / 0-click pages:")
print(zero_click_250["position_tier"].value_counts())

Total pages: 30000
Total columns: 44
Pages with 100+ impressions but 0 clicks: 6068
Pages with 250+ impressions but 0 clicks: 4166

Position tiers among 250+ impression / 0-click pages:
position_tier
page_3_5    1663
striking    1102
page_1       854
deep         463
top_3         84
Name: count, dtype: int64


## 4. Careful words: what I can and can't claim

*Write what your work will be able to say (observed, directional, decision-support) — and what it never will (causal proof, 'predicting Google').*

### What I can and can't claim

My analysis can show observed patterns in the data. For example, 6,068 pages have at least 100 impressions but zero clicks, and 4,166 pages have at least 250 impressions but zero clicks. These observations can help identify pages that may need further investigation and support decisions about content improvement and search discoverability.

However, I cannot claim that low-quality content or any specific factor causes a page to receive zero clicks. I also cannot claim that my analysis can predict Google's ranking decisions or guarantee that a page will receive more clicks after an improvement. The results will be used as directional, decision-support evidence rather than causal proof or a guarantee of Google's behavior.

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.